import pandas as pd

# List of courses to keep (copy-paste your list here)
course_list = [
    "Science",
    "Commerce",
    "Computer Science",
    "Mechanical Engineering",
    "Computer Science, Software Development",
    "Civil Engineering",
    "Business Management, Business Administration",
    "Computer Engineering, Software Engineering",
    "Electronics and Telecommunication Engineering",
    "Information Technology",
    "Electrical and Electronic Engineering",
    "Arts",
    "Electronics and Communication Engineering",
    "Biotechnology",
    "Finance, Accounts, Commerce, Economics",
    "FOUR_YEAR_BACHELOR_DEGREE",
    "Finance",
    "Hospitality and Tourism Management",
    "Diploma",
    "Psychology",
    "Architecture",
    "Pharmaceutical Sciences, Pharmacy",
    "Economics",
    "Medical Science",
    "Pharmacy",
    "Computer Technology",
    "Electrical Engineering",
    "Chemistry",
    "Business Management",
    "Agricultural Science",
    "General Studies",
    "Nursing",
    "Mathematics",
    "Business Administration",
    "Law, LLB, LLM",
    "Artificial Intelligence",
    "Marketing",
    "Computer Information Systems",
    "Electronics Engineering",
    "Physics",
    "Chemical Engineering",
    "Accounts",
    "Law",
    "Dentistry, Dental Hygiene",
    "Human Resource Management, Human Resource Development",
    "Financial Management",
    "Data Science and Analytics",
    "Language and Literature",
    "Political Science",
    "Physiotherapy",
    "Sales, Marketing",
    "Microbiology",
    "Physical Therapy, Physiotherapy",
    "English",
    "Biology, Biological Science",
    "Dentistry",
    "Human Resource Management",
    "Computing",
    "Aeronautical, Aerospace Engineering, Aviation Technology",
    "Design - Fashion, Textile, Graphics, Product",
    "International Business",
    "Media, Mass communication, Technical comunication",
    "Banking, Insurance, Risk Management, Taxation",
    "Business Analytics, Management Consulting",
    "History",
    "Food Science, Food Science and Nutrition, Food Science and Technology",
    "Advertising",
    "Design - Fashion",
    "Interior Design",
    "Life Science",
    "Biomedical Engineering",
    "Health Science, Health Management",
    "Sociology, Social Science",
    "Agribusiness",
    "LLB",
    "Information Systems, Information Technology Management",
    "Mechanical and Mechatronics Engineering",
    "Instrumentation",
    "Statistics",
    "Mass communication",
    "Pharmaceutical Sciences",
    "Journalism, Broadcasting Journalism",
    "Marketing Management",
    "Biochemistry",
    "Animation",
    "Zoology",
    "Automotive Engineering",
    "Mechatronics",
    "Human Resource Development",
    "Business Analysis",
    "Agriculture",
    "Aeronautical Engineering",
    "Journalism",
    "Information Systems",
    "Geography",
    "Architectural Engineering, Structural Engineering",
    "Visual Arts",
    "Physical Education",
    "Biology",
    "Food Science and Technology",
    "Medical Technology",
    "Forensic Science",
    "Humanities",
    "Operations",
    "Sociology",
    "Geology",
    "E-business, Digital Business, Digital Marketing",
    "Aerospace Engineering",
    "Micro biology",
    "Automotive",
    "Actuarial Science",
    "Petroleum Engineering",
    "Social Work and NGO Related Fields",
    "Product Design Engineering",
    "Construction Management",
    "Industrial Engineering, Process Engineering",
    "Banking",
    "Cyber Security, Information Security",
    "Environmental Engineering",
    "Dietetics, Nutrition",
    "Cyber Security",
    "Horticulture",
    "Nutrition",
    "Agronomy",
    "Business Analytics",
    "Financial Services",
    "Philosophy",
    "Bioinformatics",
    "Dental Hygiene",
    "Clinical Sciences",
    "Supply Chain Management",
    "Gender Studies",
    "Robotics",
    "Travel and Tourism",
    "Multimedia",
    "Mining Engineering",
    "Film, Cinematography, Interactive Media, Multimedia",
    "Food Science",
    "Food Science and Nutrition",
    "Forestry",
    "Logistics, Supply Chain Management",
    "Physiology",
    "Healthcare",
    "Digital marketing",
    "Public Health",
    "Industrial Engineering",
    "Public Relations, Public Services",
    "Medical Radiation Technology",
    "Project Management",
    "Urban Planning",
    "Textile",
    "Media",
    "Forensic Sciences",
    "International Relations",
    "Manufacturing Engineering",
    "Biological science",
    "Marine Engineering",
    "Aviation",
    "Industrial Design",
    "Health Science",
    "Criminology",
    "Liberal Arts and Studies",
    "Metallurgical Engineering, Material Engineering",
    "Sports Science, Sports, Sports Management, Exercise",
    "Software Development",
    "Fine Arts-Drawing",
    "Social Science",
    "Health Psychology",
    "Environmental Science and Technology",
    "Logistics",
    "Telecommunications Engineering",
    "Veterinary Science",
    "Culinary Skills",
    "Game Design",
    "Clinical Science",
    "Engineering Management",
    "Power Engineering",
    "Graphics",
    "Textile Engineering",
    "Web Design",
    "Architecture and Building",
    "Taxation",
    "Lab Technician",
    "Radiologic Science",
    "International Management",
    "Structural Engineering",
    "Construction",
    "Audiology - Speech",
    "Teacher Education Program",
    "Genetics",
    "Drug Development",
    "Fisheries",
    "Public Administration",
    "Biomedical Sciences",
    "Web Design, Web Applications",
    "Behavioral Sciences",
    "Film",
    "Culinary Arts",
    "Material Science, Material Science and Engineering",
    "Photography",
    "Textiles",
    "Sports Management",
    "Anthropology",
    "Information Security",
    "Product",
    "Entrepreneurship",
    "Health Management",
    "IT Business Analytics",
    "Electromechanical Engineering",
    "Event Management",
    "Computer/ Game Programming",
    "Meteorology",
    "Neuroscience",
    "Management Consulting Business Management",
    "Material Science",
    "Technical Management",
    "Transportation, Transportation Management",
    "Material Science and Engineering",
    "Physical Sciences",
    "Applied Arts - Printing",
    "Human Service",
    "Plastics Engineering",
    "Information Technology Management",
    "Fire Science, firefighting, Fire and Safety",
    "Management Consulting",
    "Music",
    "Machine Learning",
    "Occupational therapy",
    "Nanoscience, Nanotechnology",
    "Sales",
    "Animal Science",
    "Fire and Safety",
    "Elementary Education",
    "Programmer",
    "Energy Systems Technology",
    "Primary Education",
    "Renewable Energy and Materials",
    "Education Assistance",
    "Physical therapy",
    "Early Childhood Education",
    "Public Relations",
    "Educational Training",
    "Community Development",
    "Sports Science",
    "Clinical Lab",
    "Dairy",
    "Petroleum, Oil and Gas, Diesel Technology",
    "Speech pathology",
    "Architectural Engineering",
    "Mobile Communication",
    "Poultry, Dairy",
    "Marine Biology",
    "Plant Science",
    "Education Counseling",
    "Psychiatric Nursing",
    "Software Testing",
    "Aviation Technology",
    "Public policy",
    "Secondary Education",
    "Sports",
    "Astronomy, Astrophysics",
    "Geotechnical Engineering",
    "Geophysics",
    "Networking",
    "Therapist Assistant",
    "Dietetics",
    "Interactive Media",
    "Mariculture",
    "Legal Assistant, Court Support",
    "Nanotechnology",
    "Transportation Management",
    "Human Ecology, Ecology",
    "Transportation",
    "Cosmetics",
    "Developmental Service Worker",
    "Biomaterials",
    "Library",
    "Mobile Application",
    "Mining",
    "Micro electro-mechanical systems (MEMS)",
    "Respiratory Care",
    "Digital Business",
    "International Business Logistics",
    "Painting",
    "Animal Care",
    "Insurance",
    "Theology",
    "Customer Intelligence and Analytics",
    "Web Applications",
    "Physical Activity",
    "Process Engineering",
    "Cinematography",
    "Human Ecology",
    "System Engineering",
    "Earth science",
    "Organisational Learning and Leadership",
    "Organizational Management",
    "Archaeology",
    "Broadcasting Journalism",
    "Ceramics",
    "Communicative Disorder",
    "Geo physics",
    "Justice and Emergency Services",
    "Risk Management",
    "Theatre",
    "Astrophysics",
    "Nanoscience",
    "Art",
    "Oral Science",
    "Child and Youth Worker",
    "Fishery",
    "Real Estate",
    "Technical comunication",
    "Water Resource",
    "Speech Therapy",
    "Ventilation",
    "Animal Conservation",
    "Legal Assistant",
    "Property Administration",
    "Biomechanical Devices",
    "Child Care Development and Studies",
    "Geospatial Science",
    "Surveying",
    "Child Care",
    "Criminal Science",
    "Cytotechnology",
    "E- business",
    "Exercise",
    "Fitness",
    "Immunology",
    "Innovation",
    "Inter-cultural Communication",
    "Nuclear engineering",
    "Public affairs",
    "Public Services",
    "Taxation Business Analytics",
    "Aesthetics Religious Studies",
    "Cultural studies",
    "Fire Science",
    "Heating",
    "Office Administration",
    "Paper and Bioprocess",
    "Poultry",
    "Studies",
    "Studio Art",
    "Therapist assistant",
    "Conflict Analysis and Management",
    "Interdisciplinary Studies",
    "Police and Public Safety",
    "Publishing",
    "Astronomy",
    "Autism",
    "Bakery and Pastry Arts",
    "Kinesiology",
    "Sculpture",
    "Spatial Engineering",
    "Wine Making",
    "Acupuncture",
    "Court Support",
    "Creative Writing",
    "Drama",
    "Exhibition/Event",
    "Gerontology",
    "Hair Styling",
    "Interdisciplinary Engineering",
    "Midwifery",
    "Museum and Gallery Studies",
    "Nuclear Engineering",
    "Wild Life Ecosystem",
    "Aesthetics",
    "BDS",
    "Brewery",
    "Carpentry",
    "Esthetic Services",
    "Ethnic Studies",
    "Firefighting",
    "International Criminology",
    "Massage therapy",
    "Military",
    "Reading",
    "Therapeutic Recreation",
    "Welding and Fabrication",
    "Winery",
    "Woodworking"
]

# Load the matrix
matrix = pd.read_csv('hierarchical_relevancy_matrix.csv', index_col=0)

# Filter to only those in your course_list (both rows and columns)
filtered = matrix.loc[
    matrix.index.intersection(course_list),
    matrix.columns.intersection(course_list)
]

# Save the filtered matrix
filtered.to_csv('filtered_hierarchical_relevancy_matrix.csv')
print("Filtered matrix saved as filtered_hierarchical_relevancy_matrix.csv") 